name: BUILD

on:
  push:

jobs:
  x86_64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
    - run: systemctl start docker
    - run: cargo install cross
    - run: cross build --target aarch64-unknown-linux-gnu
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./target/release/pixivnp"
        token: ${{ secrets.GITHUB_TOKEN }}
