name: BUILD

on:
  push:

jobs:
  aarch64:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo apt-get install pkg-config libssl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target aarch64-unknown-linux-gnu
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "aarch64"
        artifacts: "./target/release/pixivnp"
        token: ${{ secrets.GITHUB_TOKEN }}
  amd64:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo apt-get install pkg-config libssl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "amd64"
        artifacts: "./target/release/pixivnp"
        token: ${{ secrets.GITHUB_TOKEN }}
