name: BUILD

on:
  push:

jobs:
  android:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target aarch64-linux-android
    - run: mv ./target/**/pxixvnp ./pixivnp-android
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./pixivnp-android"
        token: ${{ secrets.GITHUB_TOKEN }}
  aarch64:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo apt-get install pkg-config libssl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target aarch64-unknown-linux-gnu
    - run: mv ./target/**/pxixvnp ./pixivnp-aarch64
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./pixivnp-aarch64"
        token: ${{ secrets.GITHUB_TOKEN }}
  amd64:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo apt-get install pkg-config libssl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - run: mv ./target/**/pxixvnp ./pixivnp-amd64
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./pixivnp-amd64"
        token: ${{ secrets.GITHUB_TOKEN }}
